coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%

ignore:
  - "Projects/FileEncryption/src/Benchmark/Benchmark.cpp"
  - "Projects/FileEncryption/src/Common/main.cpp"
  - "Projects/FileEncryption/src/Core/Worker.cpp"
  - "Projects/FileEncryption/src/Core/Worker.h"
  - "Projects/FileEncryption/src/GUI/"
  - "Projects/FileEncryption/src/Tests/"
  - "Projects/PasswordManager/"

