coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%

ignore:
  - "Projects/FileEncryption/Benchmark/Benchmark.cpp"
  - "Projects/FileEncryption/Common/main.cpp"
  - "Projects/FileEncryption/Core/Worker.cpp"
  - "Projects/FileEncryption/Core/Worker.h"
  - "Projects/FileEncryption/GUI/"
  - "Projects/FileEncryption/Tests/"
