name: Sync LeetCode submissions

on:
  workflow_dispatch: 
  schedule:
    - cron: "0 0 * * *" 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run LeetCode Sync
        uses: joshcai/leetcode-sync@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
